---
swagger: "2.0"
info:
  description: "Whitelist"
  version: "1.0.0"
  title: "Whitelist"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/"
tags:
- name: "admins"
  description: "Only admin access"
- name: "addAddressScope"
  description: "Dynamic Scope for addAddress"
- name: "whitelistAddressScope"
  description: "Dynamic Scope for whitelistAddress"
- name: "ownerScope"
  description: "Dynamic Scope for owner"
- name: "userAddrScope"
  description: "Dynamic Scope for userAddr"
schemes:
- "https"
paths:
  /addAddress:
    post:
      tags:
      - "addAddressScope"
      operationId: "post_addAddress"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "addAddress_post_params"
        required: true
        schema:
          $ref: "#/definitions/addAddress_post_params"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/addAddress_post_params_response"
        400:
          description: "Error"
      x-swagger-router-controller: "AddAddressScope"
  /whitelistAddress:
    post:
      tags:
      - "whitelistAddressScope"
      - "admins"
      operationId: "post_whitelistAddress"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "whitelistAddress_post_params"
        required: true
        schema:
          $ref: "#/definitions/whitelistAddress_post_params"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/whitelistAddress_post_params_response"
        400:
          description: "Error"
      x-swagger-router-controller: "WhitelistAddressScope"
  /owner:
    get:
      tags:
      - "ownerScope"
      operationId: "get_owner"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "owner_get_params"
        required: true
        schema:
          $ref: "#/definitions/owner_get_params"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/owner_get_params_response"
        400:
          description: "Error"
      x-swagger-router-controller: "OwnerScope"
    post:
      tags:
      - "ownerScope"
      operationId: "post_owner"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "owner_post_params"
        required: true
        schema:
          $ref: "#/definitions/owner_post_params"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/owner_post_params_response"
        400:
          description: "Error"
      x-swagger-router-controller: "OwnerScope"
  /userAddr:
    get:
      tags:
      - "userAddrScope"
      operationId: "get_userAddr"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "userAddr_get_params"
        required: true
        schema:
          $ref: "#/definitions/userAddr_get_params"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/userAddr_get_params_response"
        400:
          description: "Error"
      x-swagger-router-controller: "UserAddrScope"
    post:
      tags:
      - "userAddrScope"
      operationId: "post_userAddr"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "userAddr_post_params"
        required: true
        schema:
          $ref: "#/definitions/userAddr_post_params"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/userAddr_post_params_response"
        400:
          description: "Error"
      x-swagger-router-controller: "UserAddrScope"
definitions:
  address:
    type: "string"
  receipt:
    type: "object"
    properties:
      hash:
        type: "string"
    example:
      hash: "hash"
  addAddress_post_params:
    type: "object"
    properties:
      user:
        $ref: "#/definitions/address"
      from:
        $ref: "#/definitions/address"
  addAddress_post_params_response:
    type: "object"
    properties:
      receipt:
        $ref: "#/definitions/receipt"
    example:
      receipt:
        hash: "hash"
  whitelistAddress_post_params:
    type: "object"
    properties:
      user:
        $ref: "#/definitions/address"
      from:
        $ref: "#/definitions/address"
      value:
        type: "number"
  whitelistAddress_post_params_response:
    type: "object"
    properties:
      receipt:
        $ref: "#/definitions/receipt"
    example:
      receipt:
        hash: "hash"
  owner_post_params:
    type: "object"
    properties:
      address:
        $ref: "#/definitions/address"
      from:
        $ref: "#/definitions/address"
  owner_post_params_response:
    type: "object"
    properties:
      receipt:
        $ref: "#/definitions/receipt"
    example:
      receipt:
        hash: "hash"
  owner_get_params:
    type: "object"
    properties:
      address:
        $ref: "#/definitions/address"
  owner_get_params_response:
    type: "object"
    properties:
      address:
        $ref: "#/definitions/address"
    example:
      address: {}
  userAddr_post_params:
    type: "object"
    properties:
      address:
        $ref: "#/definitions/address"
      from:
        $ref: "#/definitions/address"
  userAddr_post_params_response:
    type: "object"
    properties:
      receipt:
        $ref: "#/definitions/receipt"
    example:
      receipt:
        hash: "hash"
  userAddr_get_params:
    type: "object"
    properties:
      address:
        $ref: "#/definitions/address"
  userAddr_get_params_response:
    type: "object"
    properties:
      bool:
        type: "boolean"
    example:
      bool: true
